---
- hosts: all
  become: yes

  vars:
    awx_version: 11.2.0
    pip_package: python3-pip
    pip_install_packages:
      - docker
      - docker-compose

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.nodejs
    - geerlingguy.awx
